### PR TITLE
Ranlvor travis rework

### PR DESCRIPTION
**Pull request by Ranlvor**
- Next try on implementing a better travis_wait
- Some minor cache-optimisation

### CODE REVIEW

**Comment by uwap** [comment]
When cabal fails to install the latest version of idris do we really want it to pass the idris compilation and go on with the cached version? Also is there a reason there is no travis_wait?

**Comment by Ranlvor** [comment]
The reason for the missing travis_wait is that the travis_wait does nothing good, so I left it out so it can do nothing bad.

Is there some way to ask cabal if some software is on latest version? If there is I could write a check causing the build to break if idris is not up to date after installing it.

As an alternative I could just run cabal install twice. The first run is protected by sleep (thus imune to the 20 minute timeout), the second one is not (thus will break the build if it fails). The second one should always be fast because it'll just notice that nothing has to be changed-

**Comment by Ranlvor** [comment]
Ok. That commit should fix all the outstanding issues.
- I wrapped the thing in bash to do some magic, so I was able to restore the nice formating of https://github.com/uwap/idris-http/commit/3ead5928506060eb1781cb11201a074a27334628
- It preserves the exit-code of cabal causing the build to break if the exit-code is not 0
- It does not run cabal twice to do the trick
- The timeout-avoidance does work and I tested it
- exit-code-preserving works and I tested it

**Comment by uwap** [comment]
Really nice.

**Pull request merged**
